[bmscriptsbox]

[bmscriptsbox.info]
id = "90e04563-dd50-4665-842d-a7d48b51e54c"
name = "视频音轨移除"
desc = "基于 FFmpeg 的视频音轨移除器 | 流复制无损移除视频音轨，保留画质与字幕，一键批量处理"
version = "1.2.0"
icon = "./imgs/img.png"

[bmscriptsbox.runtime]
language = "python"
language_version = ">=3.8"
entry = "main.py"
terminal = "always"
binaries = [{name = "ffmpeg"}]

[bmscriptsbox.triggers.context_menu]
enabled = true
targets = ["files"]
filters = [".mp4", ".mkv", ".avi", ".mov", ".webm", ".flv", ".wmv", ".ts", ".m4v",
           ".mpg", ".mpeg", ".m2ts", ".mts", ".3gp", ".ogv", ".vob", ".rmvb", ".rm", ".asf"]

[bmscriptsbox.triggers.shortcut]
enabled = true
input_type = "files"
filters = [".mp4", ".mkv", ".avi", ".mov", ".webm", ".flv", ".wmv", ".ts", ".m4v",
           ".mpg", ".mpeg", ".m2ts", ".mts", ".3gp", ".ogv", ".vob", ".rmvb", ".rm", ".asf"]

[[bmscriptsbox.inputs]]
name = "target_paths"
type = "list"
exts = [".mp4", ".mkv", ".avi", ".mov", ".webm", ".flv", ".wmv", ".ts", ".m4v",
        ".mpg", ".mpeg", ".m2ts", ".mts", ".3gp", ".ogv", ".vob", ".rmvb", ".rm", ".asf"]
